### ISSUE TITLE
remove Barrier before Allgather

### ISSUE THREAD

**Issue by jeffhammond** [ParRes/ISx#6]
MPI/isx.c contains two instances of `MPI_Barrier` before `MPI_Allgather`.  `MPI_Allgather` has barrier semantics for finite count due to data dependencies and does not need this unless the MPI implementation sucks, in which case it should be a runtime option to barrier in such cases (Cray MPI already supports this via an environment variable, by the way).

**Comment by jrhemstad** [comment]
Awesome, thanks for pointing that out.
